### ISSUE TITLE
[Bug] Error joining group call

### ISSUE THREAD

**Issue by Xun66** [MarshalX/tgcalls#169]
* Client type: Pyrogram
* Version: pip install pytgcalls==2.1.0  pyrogram==1.2.20
* Example to run: [device_playout.py](https://github.com/MarshalX/tgcalls/blob/main/examples/device_playout.py) (file_playout.py also fails)
* What happened: I can see the account joined the group call but I got error as below
```
Pyrogram v1.2.20, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

tgcalls v2.0.0, Copyright (C) 2020-2021 Il`ya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3) 


[<tgcalls.AudioDevice name="BuiltInSpeakerDevice" guid="default (MacBook Air Speakers)"> , <tgcalls.AudioDevice name="BuiltInSpeakerDevice" guid="MacBook Air Speakers">]
[<tgcalls.AudioDevice name="BuiltInMicrophoneDevice" guid="default (MacBook Air Microphone)"> , <tgcalls.AudioDevice name="BuiltInMicrophoneDevice" guid="MacBook Air Microphone">]
'GroupCall' object has no attribute 'params'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/opt/homebrew/lib/python3.9/site-packages/pytgcalls/mtproto/pyrogram_bridge.py", line 63, in _process_update
    await self._update_to_handler[type(update)](update)
  File "/opt/homebrew/lib/python3.9/site-packages/pytgcalls/mtproto/pyrogram_bridge.py", line 75, in _process_group_call_update
    call = GroupCallWrapper(update.call.id, update.call.params)
AttributeError: 'GroupCall' object has no attribute 'params'
```

Any idea about the reason for this error?

**Comment by MarshalX** [comment]
please install dev version of pytgcalls by calling `pip install -U pytgcalls==3.0.0.dev19`
