### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by json1c** [MarshalX/tgcalls#177]
Traceback:

```Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 195, in communicate
    stdin, stdout, stderr = await tasks.gather(stdin, stdout, stderr)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/telegram-raid-botnet/functions/voice_chat.py", line 27, in join_and_play
    await app.join_group_call(
  File "/usr/lib/python3.10/dist-packages/pytgcalls/methods/groups/join_group_call.py", line 169, in join_group_call
    await stream.check_pipe()
  File "/usr/lib/python3.10/dist-packages/pytgcalls/types/input_stream/audio_piped.py", line 61, in check_pipe
    header = await FFprobe.check_file(
  File "/usr/lib/python3.10/dist-packages/pytgcalls/ffprobe.py", line 66, in check_file
    stdout, stderr = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 460, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<VoicePlayFunc.join_and_play() done, defined at /root/telegram-raid-botnet/functions/voice_chat.py:20> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 195, in communicate
    stdin, stdout, stderr = await tasks.gather(stdin, stdout, stderr)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/telegram-raid-botnet/functions/voice_chat.py", line 27, in join_and_play
    await app.join_group_call(
  File "/usr/lib/python3.10/dist-packages/pytgcalls/methods/groups/join_group_call.py", line 169, in join_group_call
    await stream.check_pipe()
  File "/usr/lib/python3.10/dist-packages/pytgcalls/types/input_stream/audio_piped.py", line 61, in check_pipe
    header = await FFprobe.check_file(
  File "/usr/lib/python3.10/dist-packages/pytgcalls/ffprobe.py", line 66, in check_file
    stdout, stderr = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 460, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<VoicePlayFunc.join_and_play() done, defined at /root/telegram-raid-botnet/functions/voice_chat.py:20> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 195, in communicate
    stdin, stdout, stderr = await tasks.gather(stdin, stdout, stderr)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/telegram-raid-botnet/functions/voice_chat.py", line 27, in join_and_play
    await app.join_group_call(
  File "/usr/lib/python3.10/dist-packages/pytgcalls/methods/groups/join_group_call.py", line 169, in join_group_call
    await stream.check_pipe()
  File "/usr/lib/python3.10/dist-packages/pytgcalls/types/input_stream/audio_piped.py", line 61, in check_pipe
    header = await FFprobe.check_file(
  File "/usr/lib/python3.10/dist-packages/pytgcalls/ffprobe.py", line 66, in check_file
    stdout, stderr = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 460, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by MarshalX** [comment]
Wrong lib. You are using py-tgcalls. This repository of **pytgcalls**

**Comment by json1c** [comment]
oops
