### ISSUE TITLE
Can't install pytgcalls[pyrogram] on venv

### ISSUE THREAD

**Issue by sistematico** [MarshalX/tgcalls#187]
```
pip install pytgcalls[pyrogram] 
zsh: no matches found: pytgcalls[pyrogram]
```

Python 3.10.8
pip 22.2.2

Using Arch Linux.

**Comment by MarshalX** [comment]
You forgot to add "

**Comment by MarshalX** [comment]
pip install "pytgcalls[pyrogram]"

Try this. Moreover I recommend to use only dev version of the lib 

pip install pytgcalls==3.0.0.dev22
Examples: https://gist.github.com/MarshalX/3c99fcae532178928d93a7aae6f0efde

**Comment by sistematico** [comment]
```
/home/lucas/music-bot/main.py:34: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(main(pyro_client))
tgcalls v3.0.0.5 DEV, Copyright (C) 2020-2021 Il`ya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3) 


Task exception was never retrieved
future: <Task finished name='Task-59' coro=<GroupCallBase.__emit_join_payload_callback.<locals>._() done, defined at /home/lucas/music-bot/venv/lib/python3.10/site-packages/pytgcalls/implementation/group_call_base.py:173> exception=BotMethodInvalid('Telegram says: [400 BOT_METHOD_INVALID] - The method can\'t be used by bots (caused by "phone.JoinGroupCall")')>
Traceback (most recent call last):
  File "/home/lucas/music-bot/venv/lib/python3.10/site-packages/pytgcalls/implementation/group_call_base.py", line 180, in _
    await self.mtproto.join_group_call(
  File "/home/lucas/music-bot/venv/lib/python3.10/site-packages/pytgcalls/mtproto/pyrogram_bridge.py", line 211, in join_group_call
    response = await self.client.send(
  File "/home/lucas/music-bot/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/home/lucas/music-bot/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/lucas/music-bot/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/home/lucas/music-bot/venv/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: Telegram says: [400 BOT_METHOD_INVALID] - The method can't be used by bots (caused by "phone.JoinGroupCall")
```

**Comment by rojvv** [comment]
@sistematico That is not related to this issue.

**Comment by sistematico** [comment]
> @sistematico That is not related to this issue.

Sure, thank you.

**Comment by rojvv** [comment]
You're welcome.
