### ISSUE TITLE
Error on get full chat

### ISSUE THREAD

**Issue by tilibougnia** [MarshalX/tgcalls#84]
Hi MarshalX

I use the sample recorder_as_smart_plugin.py

I just changed the filter to work on all call but when I receive call. I always this error.

`Can't get full chat by xxxxxxxxx
Traceback (most recent call last):
  File "/home/tgndev/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/tgndev/dev/pyrogramclient/plugins/handlers.py", line 22, in record_from_voice_chat
    await GROUP_CALL.start(m.chat.id)
  File "/home/tgndev/.local/lib/python3.8/site-packages/pytgcalls/group_call_native.py", line 348, in start
    await self.get_group_call(group)
  File "/home/tgndev/.local/lib/python3.8/site-packages/pytgcalls/group_call_native.py", line 283, in get_group_call
    raise RuntimeError(f'Can\'t get full chat by {group}')
RuntimeError: Can't get full chat by xxxxxxxxx`

Kind regards

**Comment by MarshalX** [comment]
Hello. Are you talking about private calls or group calls? Private calls currently not available

**Comment by tilibougnia** [comment]
Oh ok, sorry, yes I 'm talking about private calls.

Thanks you for the answer

Kind regards
